cors:
    originPatters: http://localhost:8080,http://localhost:3000
spring:
    jpa:
        show-sql: false
        open-in-view: false
        hibernate:
            ddl-auto: none
    datasource:
        url: jdbc:postgresql://localhost:5432/springaws
        username: postgres
        password: admin
        driverClassName: org.postgresql.Driver
springdoc:
    pathsToMatch: /api/**/v1/**
    swagger-ui:
        use-root-path: true